/**
 * Generates D1 seed SQL from lib/seed-data.ts.
 *
 * Usage:
 *   pnpm dlx tsx scripts/seed-d1.ts
 *   pnpm exec wrangler d1 execute kitarsemula-db --local  --file .wrangler/seed.sql
 *   pnpm exec wrangler d1 execute kitarsemula-db --remote --file .wrangler/seed.sql
 *
 * Uses INSERT ... ON CONFLICT so re-running is safe (upsert on slug). Writes
 * UTF-8 without a BOM — Wrangler rejects UTF-16, which shell redirection on
 * Windows commonly produces.
 */

import { mkdirSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { SEED_CENTERS } from '../lib/seed-data';

const OUT_PATH = join(process.cwd(), '.wrangler', 'seed.sql');

function sql(value: string | number | null): string {
  if (value === null) return 'NULL';
  if (typeof value === 'number') return String(value);
  return `'${value.replace(/'/g, "''")}'`;
}

// No explicit BEGIN/COMMIT: remote D1 rejects SQL transactions
// ("use state.storage.transaction()"). Wrangler applies the file as-is.
const lines: string[] = ['-- Generated by scripts/seed-d1.ts — do not edit by hand.'];

for (const c of SEED_CENTERS) {
  const columns = [
    'id',
    'slug',
    'name',
    'address',
    'state',
    'area',
    'latitude',
    'longitude',
    'phone',
    'website_url',
    'google_maps_url',
    'accepted_items',
    'tags',
    'opening_hours',
    'status',
    'verification_status',
    'upvote_count',
    'downvote_count',
    'notes',
    'created_at',
    'updated_at',
    'last_verified_at',
  ];

  const values = [
    sql(c.id),
    sql(c.slug),
    sql(c.name),
    sql(c.address),
    sql(c.state),
    sql(c.area),
    sql(c.latitude),
    sql(c.longitude),
    sql(c.phone ?? null),
    sql(c.website_url ?? null),
    sql(c.google_maps_url ?? null),
    sql(JSON.stringify(c.accepted_items)),
    sql(JSON.stringify(c.tags)),
    sql(JSON.stringify(c.opening_hours)),
    sql(c.status),
    sql(c.verification_status),
    sql(c.upvote_count),
    sql(c.downvote_count),
    sql(c.notes ?? null),
    sql(c.created_at),
    sql(c.updated_at),
    sql(c.last_verified_at ?? null),
  ];

  const updates = columns
    .filter((col) => col !== 'slug')
    .map((col) => `${col} = excluded.${col}`)
    .join(', ');

  lines.push(
    `INSERT INTO centers (${columns.join(', ')}) VALUES (${values.join(', ')})\n  ON CONFLICT (slug) DO UPDATE SET ${updates};`,
  );
}

lines.push('-- end');

mkdirSync(dirname(OUT_PATH), { recursive: true });
writeFileSync(OUT_PATH, lines.join('\n') + '\n', 'utf-8');
console.log(`Wrote seed SQL for ${SEED_CENTERS.length} centers to ${OUT_PATH}`);
